sudo: required
services:
    - docker

before_install:
    - docker build -t porzechowski/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true porzechowski/docker-react npm run test
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-317792549218"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY